import { test, expect } from "@playwright/test";
import { launchWithExtension, cleanup } from "./helpers/extension";
import { warmUpGoogle, searchGoogle, AI_QUERIES } from "./helpers/google";
import { assertAllAIElementsHidden } from "./helpers/detectors";
import type { BrowserContext, Page } from "@playwright/test";

/**
 * AI hiding tests — run WITH the extension.
 * Navigates to live Google and confirms all AI elements are hidden.
 */

let context: BrowserContext;
let page: Page;
let userDataDir: string;

test.describe("AI elements hidden with extension", () => {
  test.beforeAll(async () => {
    const session = await launchWithExtension();
    context = session.context;
    page = session.page;
    userDataDir = session.userDataDir;
    await warmUpGoogle(page);
  });

  test.afterAll(async () => {
    await cleanup({ context, page, userDataDir });
  });

  test.afterEach(async () => {
    await page.waitForTimeout(3000);
  });

  test("AI Overview elements are not visible on search results", async () => {
    await searchGoogle(page, AI_QUERIES[0]);

    await assertAllAIElementsHidden(page);
  });

  test("AI Mode tab and buttons are not visible", async () => {
    // Use a different query to broaden coverage
    await searchGoogle(page, AI_QUERIES[1]);

    await assertAllAIElementsHidden(page);
  });

  test("no visible heading contains AI text patterns", async () => {
    await searchGoogle(page, AI_QUERIES[2]);


    const visibleAIText = await page.evaluate(() => {
      const headings = document.querySelectorAll("h1, h2, h3, [role='heading']");
      const matches: string[] = [];
      for (const h of headings) {
        const text = h.textContent?.trim().slice(0, 50) || "";
        if (/^ai overview/i.test(text) || /^ai mode/i.test(text) || /generated by ai/i.test(text)) {
          const style = window.getComputedStyle(h);
          if (style.display !== "none" && style.visibility !== "hidden") {
            matches.push(text);
          }
        }
      }
      return matches;
    });

    expect(visibleAIText).toEqual([]);
  });

  test("normal search results are still visible", async () => {
    await searchGoogle(page, "weather");


    // The main search container should exist
    const searchContainer = page.locator("#search, #rso");
    await expect(searchContainer.first()).toBeVisible();

    // At least one normal result should be visible
    const normalResults = page.locator("div.g, [data-sokoban-container], [data-hveid]");
    const count = await normalResults.count();
    expect(count).toBeGreaterThan(0);

    // Verify at least one is actually visible
    let anyVisible = false;
    for (let i = 0; i < Math.min(count, 10); i++) {
      if (await normalResults.nth(i).isVisible().catch(() => false)) {
        anyVisible = true;
        break;
      }
    }
    expect(anyVisible).toBe(true);
  });
});
