/*
 * Google renders AI Overviews asynchronously after initial page load, so CSS
 * alone can miss late-arriving elements with dynamic class names. This observer
 * removes them by text-content heuristics as they appear.
 */

(function () {
  "use strict";

  const AI_TEXT_PATTERNS = [
    /^ai overview/i,
    /^ai mode/i,
    /generated by ai/i,
  ];

  function looksLikeAIOverview(el) {
    if (!el || !el.textContent) return false;
    const firstChars = el.textContent.trim().slice(0, 50);
    return AI_TEXT_PATTERNS.some((re) => re.test(firstChars));
  }

  function nuke(el) {
    if (!el || el.dataset.aiBlockerHit) return;
    el.dataset.aiBlockerHit = "1";
    el.style.setProperty("display", "none", "important");
  }

  function scan(root) {
    // AI Overview headings are typically h1/h2 with "AI Overview" text
    const headings = root.querySelectorAll?.("h1, h2, h3, [role='heading']");
    if (!headings) return;
    for (const h of headings) {
      if (looksLikeAIOverview(h)) {
        // Walk up to the nearest container and hide it
        let container = h.closest(
          "div[data-hveid], div[jsname], div[data-mcareid], section, g-section-with-header"
        );
        if (!container) container = h.parentElement;
        if (container) nuke(container);
      }
    }

    // Also catch AI Mode tab links that slipped past CSS
    const aiModeLinks = root.querySelectorAll?.("a[href*='udm=50'], a[href*='/aimode']");
    if (aiModeLinks) {
      for (const a of aiModeLinks) {
        const container = a.closest("div[role='listitem'], div[role='tab'], li") || a;
        nuke(container);
      }
    }

    // Hide any button or link whose visible text says "AI Mode"
    const clickables = root.querySelectorAll?.("button, a");
    if (clickables) {
      for (const el of clickables) {
        const text = el.textContent?.trim() || "";
        if (/^ai mode$/i.test(text) || /\bai mode\b/i.test(text)) {
          nuke(el);
        }
      }
    }
  }

  // Initial pass once DOM exists
  if (document.body) {
    scan(document);
  } else {
    document.addEventListener("DOMContentLoaded", () => scan(document), { once: true });
  }

  // Watch for lazy-loaded AI content
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) {
      for (const node of m.addedNodes) {
        if (node.nodeType === 1) {
          scan(node);
        }
      }
    }
  });

  const start = () => {
    if (document.body) {
      observer.observe(document.body, { childList: true, subtree: true });
    } else {
      requestAnimationFrame(start);
    }
  };
  start();

  // Clean the URL if Google's SPA navigation lands us on ?udm=50
  function cleanUrl() {
    try {
      const u = new URL(location.href);
      if (u.searchParams.get("udm") === "50") {
        u.searchParams.delete("udm");
        location.replace(u.toString());
      }
    } catch {}
  }
  cleanUrl();
  window.addEventListener("popstate", cleanUrl);
})();
